CMakeLists.txt, src/engine/basics/point.cxx, src/engine/basics/point.hxx, src/engine/basics/resources.cxx, src/engine/basics/vectorMatrix.cxx, src/engine/basics/vectorMatrix.hxx, src/engine/cell.cxx, src/engine/engine.cxx, src/engine/sprite.cxx, src/engine/ui/uiElement.cxx, src/game.cxx
This changes Point into a simple struct. This allows us to use brace initialization to construct its elements. e.g., Point{1, 2, 3, 4} would set x to 1, y to 2, z to 3, and height to 4. This also means that, if a function returns a Point, you can simply specific the braces {1, 2, 3, 4} without having to say Point.
=> Simplify the point class

.lgtm.yml, src/engine/uiManager.cxx
Fix LGTM Alert for third party libraries by excluding them
=> Exclude thirdparty libraries from LGTM scans

.gitignore, .travis.yml, appveyor.yml, cmake/pmm.cmake
PMM 1.4.1 adds the Clean command that removes temporary source and build folders in the local conan cache
=> 🔧 Upgrade to pmm 1.4.1 

src/engine/EventManager.cxx, src/engine/EventManager.hxx, src/engine/basics/Timer.cxx
no need for remove Timer,
when we iterate over timers in function EventManager::checkEvents  and checkout every timer.
we do another loop and check which timers got timeout and remove it ,
it is possible to remove elements from vector while iterating over  it using the method I used.
also used vector instead of set because set is immutable.
the method I used for removing elements is erase which the return value is 
"An iterator pointing to the new location of the element that followed the last element erased by the function call."
so by using   it = timers.erase(it),  it should point to the next element while removing the current.
=> fixed #179, changed EventManager timer list implementation.

src/engine/ui/widgets/Button.hxx, src/engine/ui/widgets/Checkbox.hxx, src/engine/ui/widgets/Combobox.hxx, src/engine/ui/widgets/Frame.hxx, src/engine/ui/widgets/Image.hxx, src/engine/ui/widgets/Slider.hxx, src/engine/ui/widgets/Text.hxx, src/engine/ui/widgets/TextField.hxx, src/engine/ui/widgets/Tooltip.hxx
The `setOpacity` method for the Image widget now checks if the alpha level given is between 0 and 255 before changing the opacity. If not, the method logs an error. 
Also added some documentation to UI widget classes.
=> Image opacity modifications and widget documentation

data/resources/data/TileData.json
When I uploaded the new images, I changed the name of the Power Plant, Nature and Water directories to power plant, nature and water. This has broken the itch.io build leaving it unable to find the images for these tiles. I have changed the paths to the tiles in TileData.json to correct this.
This issue didn't appear in my source build, only in the itch.io build that I downloaded to test it out. If you would like to test it, download the itch.io build and paste the changed TileData.json into it and you'll see it working. 
Thanks to KingTut for pointing this one out.
=> HOTFIX to fix path issue in Tiledata.json

src/Game.cxx, src/Game.hxx, src/services/AudioMixer.cxx, src/services/AudioMixer.hxx
This branch fixes the issues with the slow startup when loading the sounds. It would be best to be reviewed by someone who was having issues with the sound loading blocking the startup of the UI thread.
I have started a new thread in the AudioMixer that will free up the UI thread while the sounds are loading. This allows the game to start instantly again, however, this thread only ends once all sounds have loaded and it will block the game quitting while waiting for it to join, so basically I have moved the problem from when you start the game to when you are quitting the game but from a usability perspective, this is better (it definitely isn't worse). 
To test this; start the game, does it start quickly? when you start a new game, make sure the main theme music still plays.
=> Fix sound startup

README.md
The build instructions and coding guidelines links were still mentioning the original name of the repo.
=> Fix Github links still having JimmySnails in URL

src/engine/EventManager.cxx
This update adds camera panning with WASD keys.
Camera panning has boundaries that it cannot go past.
The boundaries generally work for different zoom levels, but depends on screen width and screen height.
Boundaries aren't included for the other panning methods.
=> Camera Panning with WASD keys, bounds included

src/Events.hxx, src/Game.cxx
I am re-implementing 3D audio after the new update that added continuous music and sound effects use.
Songs playing in mono were painful to listen to so I just played the mono song twice in left and right to simulate stereo. 
This is a workaround since SDL_Mixer can only load sound exclusively in either mono or stereo.
I changed the Coordinate3D type to double since it adds more resolution to OpenAL 3D audio placement.
=> 3D Audio Implementation added for song playing and nature sounds

src/Game.cxx, src/services/AudioMixer.cxx, src/services/AudioMixer.hxx
I made a mistake of calling 2 triggers to play music at 2 different locations. I thought this would play the same song and it did when I tested it. 
However, it plays 2 different songs at 2 locations.
I removed this and just placed the music at one location that is more comfortable to hear.
=> Fixing mistake in 3D audio

src/engine/EventManager.cxx, src/engine/Map.cxx, src/engine/Map.hxx
this fix is regarding buildings bigger than 1x1.
all tiles of already existed building is now highlighted instead of base corner tile.
=> occupied tile highlight fix, highlight all nodes of existing object.

src/engine/Map.cxx, src/engine/Sprite.cxx, src/engine/Sprite.hxx, src/engine/basics/Camera.cxx, src/engine/basics/Camera.hxx, src/engine/basics/isoMath.cxx
The clipRect (sourceRect) is smaller by one pixel than the destRect. I think this is related to rounding errors.
In this PR, i made it 1px taller and now the tile selection jumpyness is gone
=> Fix Tileselection

ReleaseNotes.txt, src/engine/EventManager.cxx, src/engine/GameObjects/MapNode.cxx, src/engine/GameObjects/MapNode.hxx, src/engine/Map.cxx, src/engine/Map.hxx, src/engine/basics/GameStates.hxx, src/engine/common/enums.hxx
=> Fix demolish tool

src/engine/WindowManager.cxx
mode 0 (the biggests available resolution) caused an exception due to a wrong check
=> Allow mode 0 (1920x1080) resolution to be set

.travis.yml, CMakeLists.txt, conanfile-win.txt.in, conanfile.txt.in, tools/format-files.sh, tools/format-json.js
+ This makes Vulkan optional and disabled by default.
+ This makes our travis-ci GCC build use conan
+ This makes our tool scripts able to be ran from anywhere (before, we would need to be in the root directory of the project)
=> Make Vulkan dependency optional, fix travis-ci, and fix tool scripts

CMakeLists.txt, src/engine/Map.cxx
Test results are attached. I would say roughly 2 times faster than older implementation.
Old implementation number of calls to the isClickWithinTile function.
Which node.
New implementation number of calls to the isClickWithinTile function.
May 02 17:34:29 - [INFO] - -----------------------------------------------------
May 02 17:34:29 - [INFO] - Old loops: 1017
May 02 17:34:29 - [INFO] - Found: 19 : 122
May 02 17:34:29 - [INFO] - New loops: 543
May 02 17:34:29 - [INFO] - -----------------------------------------------------
May 02 17:34:18 - [INFO] - -----------------------------------------------------
May 02 17:34:18 - [INFO] - Old loops: 1152
May 02 17:34:18 - [INFO] - Found: 0 : 125
May 02 17:34:18 - [INFO] - New loops: 628
May 02 17:34:18 - [INFO] - …
=> Optimize findNodeInMap function

CMakeLists.txt, src/util/LOG.cxx
On Android, stdout is not written to the adb log. We have to use android_log_print instead.
I added it, but it doesn’t feature any other loglevels than info yet
=> use __android_log_print instad of cout for android logs

src/view/Window.cxx
This resolves an issue where the cursor was captured within a window
=> Fixing a problem where cursor was captured

CMakeLists.txt, src/CMakeLists.txt
- Someone broke the macOS build by not adding the resources into the correct dir.
bin/Cytopia.app/Contents/MacOS
instead of 
bin/Cytopia.app/Contents/Resources
- Language folder was missing in resources
- resources folder was redundantly added to root dir where it is not needed
=> Fix mac os

src/engine/basics/tileData.hxx
Previously the documentation page for [TileData](https://cytopia-docs.netlify.app/structtiledata) showed the wrong comments for each variable because the /// was after the member. Adding < after the /// fixes this.
I also changed the comment before TileSetData so the struct would show in documentation, which it didn't before this change.
=> Fixed doxy syntax to fix documentation for variables.

src/engine/TileManager.cxx, src/engine/TileManager.hxx
Returning a reference to a stack variable is UB.
=> Fix possible crash when calling TileManager::getRandomTileIDForZoneWithRandomSize

src/engine/GameObjects/MapNode.hxx, src/engine/Map.cxx, src/engine/map/TerrainGenerator.cxx
- Fixed the order in which tiles are drawn
- Fixed z-order coordinate in mapnodes (which was always utterly wrong, but never used)
- Added an option to set z index for map nodes (it's not possible to set it otherwise and i don't understand the terrain gen code enough to make changes there)
The coordinates origin (0,0) is the top left node. So i changed the order in which the tiles are rendered.
Nodes are now rendered in this order:
Fixes  #404
Fixes #419 
Fixes #726
Fixes #725
=> Fix z order

src/services/GameClock.inl.hxx
Summary:
`assert` is not defined in template header file. 
Compiler states: 
* `error: there are no arguments to ‘assert’ that depend on a template parameter, so a declaration of ‘assert’ must be available`
=> Fix compilation error by adding missing header-file definition

src/engine/ResourcesManager.cxx
As title.
* Affected functions cannot `return` after a `throw`, as `throw` [will cause a `std::runtime_error`. ](https://github.com/CytopiaTeam/Cytopia/blob/3f128b9442f9e1dc62e33679ed4a77bf327bdd1b/src/util/Exception.hxx#L10)
* Removed lines to help code-clarity.
=> Removed line-consecutive throw-return statements

data/resources/settings.json, src/engine/basics/Settings.cxx, src/engine/basics/Settings.hxx, src/engine/common/JsonSerialization.hxx, src/util/Exception.hxx, src/util/LOG.cxx, src/util/LOG.hxx, tests/CMakeLists.txt
Sometimes we're not allowed to write new files, and the error log isn't needed in most cases, so don't write it if not explicitly enabled.
=> Add a setting option to write the error log to a file

src/engine/GameObjects/MapNode.cxx
As titled.
---
Some reasons for changeset:
* Recommended and helpful suggestion from the C++ Core Guidelines:
[C.49: Prefer initialization to assignment in constructors.](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c49-prefer-initialization-to-assignment-in-constructors)
* Size of codebase is reduced.
---
Great project BTW! :tada:
=> Minor refactor for codebase to prefer constructor initializer lists

.github/workflows/build-game.yml, CMakeLists.txt, src/CMakeLists.txt
This adds CI checks and CMake options to enable Address/Undefined Behaviour/Thread Sanitizers (https://github.com/google/sanitizers/) which are available for GCC and Clang.
This improves detection of things like buffer overruns, integer overflows and data races.
=> Add options to build with ASan/UBSan/TSan

src/Game.cxx, src/Game.hxx, src/main.cxx
* Implements `namespace Cytopia` to a variety of translation units.
* This PR's changeset moves various functions (function symbols) off the `global` namespace.
* This PR is needed / advisable as it helps improve argument-dependent lookups (ADL), software debugging, reduces pollution of the global namespace and namespace-encapsulation of various datatypes.
---
_For example:_
Before changeset:
* Previously the translation unit's function `Game::run` (symbol) was "listed" under the `global` namespace.
```
./src/CMakeFiles/Cytopia.dir/Game.cxx.o:0000000000001222 T _ZN4Game3runEb
```
After changeset:
* `Game::run` is now correctly aliased behind / as part of the `Cytopia` namespace.
```
./src/CMakeFiles/Cytopia.dir/Game.cxx.o:0000000000001222 T _ZN7Cytopia4Game3runEb
```
---
Further future …
=> game: Implement `namespace Cytopia`

src/engine/EventManager.cxx, src/engine/EventManager.hxx, src/engine/GameObjects/MapNode.cxx, src/engine/Map.cxx, src/engine/Map.hxx, src/engine/common/enums.hxx
Middle click eyedropper tool feature is supported now!
We can pick nearly all kinds of object in the map like buildings, powerlines, flora, etc. Just like what we have to do in the UI elements.
https://user-images.githubusercontent.com/41318515/167623154-647f9e72-0202-4965-b4b8-c51f741291b3.mov
Related issue: #910
=> Implement middle click eyedropper tool feature

src/engine/WindowManager.cxx
why: some screen resolutions show with different refresh rates and bpp.
task: https://github.com/CytopiaTeam/Cytopia/issues/855
=> ui: settings: allow only unique screen resolution

src/engine/EventManager.cxx, src/engine/EventManager.hxx
This pr provided an ad-hoc solution to #800. A flag is used to protect the action of putting a tile. After implemented this, multi tile placement will always work well in my environment(Mac).
The event manager should to be refactored, this pr might be a temporary fix to the annoying bug.
=> Multi-tile placement (#800)

src/CMakeLists.txt, tests/CMakeLists.txt, tests/main.cxx
why: dependencies include headers not attended to solution via cmake
=> cmake: windows: fix visual studio solution generation

src/CMakeLists.txt, tests/CMakeLists.txt, tests/main.cxx
`CONAN_` vars should not be used in `src/CMakeLists.txt` or `tests/CMakeLists.txt`, since you can build without Conan on windows
=> Revert "cmake: windows: fix visual studio solution generation (#933)"

src/Game.cxx, src/Game.hxx, src/main.cxx
task: https://github.com/CytopiaTeam/Cytopia/issues/330
=> game: options: chose render driver with command-line parameter

README.md
while building on Linux noticed that this library missing from prerequisites 
added missing prerequisites, libpng
=> added missing prerequisites, libpng

src/engine/UIManager.cxx
Minor edits to prefer standard library function `std::none_of` over `std::find`.
=> uimanager: Prefer standard algorithm - `std::none_of`

src/engine/EventManager.cxx, src/engine/map/MapFunctions.cxx, src/engine/map/MapFunctions.hxx, src/game/ui/BuildMenu.cxx
This is an overall naïve implementation, in the sense that it copies the height of the initial selected node and applies it to the whole area.
The main factors for code complexity stem from:
- my assumption that we want to level an arbitrary area and not always a rectangular area, which prevents some checks
- my personal requirements for levelling behavior on sloped nodes (see below)
The first point might be mitigated though by deciding on only having rectangular selection for levelling (see #1016).
Slopes should lower the terrain when the selection is pulled from the lower side:
levels to
They should raise the terrain when the selection goes the other way:
levels to
Edged slopes should behave the same:
levels to
In all screenshots the rectangle was dragged up from the lowest edge (I …
=> Implemented "level terrain" feature, fix #28

src/MainMenu.cxx, src/engine/Layout.hxx, src/engine/UIManager.cxx, src/engine/UIManager.hxx, src/engine/WindowManager.cxx, src/engine/basics/Camera.cxx, src/engine/basics/GameStates.hxx, src/engine/basics/tileData.hxx, src/game/ui/BuildMenu.hxx, src/game/ui/GameTimeMenu.cxx, src/game/ui/LoadMenu.cxx, src/game/ui/LoadMenu.hxx, src/game/ui/PauseMenu.cxx, src/game/ui/SettingsMenu.cxx, src/scripting/ImGuiAngelscript.cxx, src/services/AudioMixer.cxx
As mentioned in [this discussion](https://github.com/CytopiaTeam/Cytopia/pull/1017#issuecomment-1221613544), the formatting was off in a few places. This PR brings all the parts that the script can correct to good state.
=> Corrected formatting by running `format-files.sh` script.

src/engine/GameObjects/MapNode.cxx, src/engine/map/MapFunctions.cxx
As mentions in #892, we have a problem when load saved game, the buildings(> 1x1) will be duplicated.
Here is the screenshot, the duplicate buildings problem has been fixed.
=> fix: duplicate buildings when load saved game (#892)

src/engine/GameObjects/MapNode.cxx
As we may have sea, river and lake in our map. It is hard for us to build a city without cross water roads. 
So we can allow road be placed on water, actually this is a simplified bridge.
=> tile: allow road be placed on water

src/engine/EventManager.cxx, src/engine/EventManager.hxx, tests/CMakeLists.txt, tests/engine/EventManager.cxx
EventManager.{c.h}xx:
* Added namespace: `detail`.
* Added function: `updatePlacementMode`
* Added some test cases for: `EventManager`: `updatePlacementMode`.
=> eventmanager: Extracted some logic to an external function
