CytopiaTeam/Cytopia

- resources/settings.json
- src/engine/basics/point.hxx
- src/engine/basics/resources.cxx
- src/engine/basics/resources.hxx
- src/engine/basics/vectorMatrix.cxx
- src/engine/basics/vectorMatrix.hxx
- src/engine/cell.cxx
- src/engine/cell.hxx
- src/engine/engine.cxx
- src/engine/engine.hxx
- src/engine/sprite.cxx
- src/engine/sprite.hxx
- src/engine/textureManager.cxx
- src/engine/textureManager.hxx
- src/game.cxx
Move functions to determine a cells neighbor and draw the slopes to the vectormatrix class
> Refactor vectorMatrix class

- CMakeLists.txt
- README.md
- cmake_modules/FindSDL2.cmake
- cmake_modules/FindSDL2_image.cmake
- cmake_modules/FindSDL2_ttf.cmake
> Update the build system to a modern CMake style

- .travis.yml
- CMakeLists.txt
Use CPACK to create packages automatically for Debian packages.
> Add automatic package creation for debian

- CMakeLists.txt
- resources/data/UILayout.json
- src/engine/basics/log.hxx
- src/engine/basics/vectorMatrix.hxx
- src/engine/eventManager.cxx
- src/engine/textureManager.cxx
- src/engine/ui/combobox.cxx
- src/engine/ui/combobox.hxx
- src/engine/ui/text.cxx
- src/engine/ui/text.hxx
- src/engine/ui/textField.cxx
- src/engine/ui/textField.hxx
- src/engine/ui/uiElement.cxx
- src/engine/ui/uiElement.hxx
- src/engine/uiManager.cxx
- src/engine/uiManager.hxx
Add a textfield class to draw multiple texts beneath each other and finish comboboxes
> WIP - Comboboxes and textField classes

- CMakeLists.txt
- resources/data/UILayout.json
- src/engine/basics/signal.hxx
- src/engine/basics/utils.hxx
- src/engine/eventManager.cxx
- src/engine/eventManager.hxx
- src/engine/textureManager.cxx
- src/engine/textureManager.hxx
- src/engine/ui/button.cxx
- src/engine/ui/button.hxx
- src/engine/ui/checkbox.cxx
- src/engine/ui/checkbox.hxx
- src/engine/ui/combobox.cxx
- src/engine/ui/combobox.hxx
- src/engine/ui/uiElement.cxx
- src/engine/ui/uiElement.hxx
- src/engine/uiManager.cxx
- src/engine/uiManager.hxx
- src/game.cxx
Implement signal-slot functionality for registering callback functions to ui elements.
Provide an interface for UI Elements to react on mouse events instead of doing that in a function in the UI Manager.
Refactoring in general.
> User Interface improvements - Signal slot implementation

- .gitignore
Someone at some point is going to need this.
😰💧
<sub>And they can just use `.git/info/exclude`, but, oh, well.</sub>
> Ignore Vim caches

- src/engine/uiManager.cxx
- src/engine/uiManager.hxx
Simple refactoring, to improve readability.
> Refactor UIManager

- src/TileDataUi/TileData.cxx
- src/TileDataUi/TileData.hxx
- src/TileDataUi/TileDataUi.cxx
- src/TileDataUi/TileDataUi.hxx
- src/TileDataUi/main.cxx
- src/engine/basics/signal.hxx
- src/game.cxx
- src/game.hxx
- src/main.cxx
Some formatting was incorrect, I have no idea why (probably vscode?). I added separate commit for that.
> Add class Game and protect main() function against unhandled exceptions.

- src/engine/basics/camera.cxx
- src/engine/basics/camera.hxx
- src/engine/eventManager.cxx
- src/engine/eventManager.hxx
Implement touch gestures.
Two Fingure gestures for pan and pinch to zoom
> Touch gestures

- src/engine/basics/settings.cxx
- src/engine/basics/settings.hxx
- src/engine/ui/basics/Layout.cxx
- src/engine/uiManager.cxx
- src/engine/windowManager.cxx
Fixes layouting when changing resolutions and full screen modes
> Fix layouting when switching screen resolutions

- .travis.yml
- appveyor.yml
> 🔧 Remove big folders from build cache

- CMakeLists.txt
- src/game.cxx
- Make SDL_Mixer optional
- Don't use lsb-release on mac
> CMake improvements

- CMakeLists.txt
- src/engine/eventManager.cxx
- src/engine/map.cxx
- src/engine/sprite.cxx
- src/engine/uiManager.cxx
- src/game.cxx
Added https://github.com/jonasmr/microprofile
This can may be useful to see the performance impact of #133
> Added microprofile

- src/engine/GameObjects/mapNode.cxx
- src/engine/GameObjects/mapNode.hxx
- src/engine/basics/settings.cxx
- src/engine/eventManager.cxx
- src/engine/map.cxx
- src/engine/sprite.cxx
- src/engine/sprite.hxx
- src/engine/uiManager.cxx
- Fixes autotiling (non tile-able sprites were placed wrong) 
- Fixes tileselection by checking both building layer (which can be smaller then the actual tile) and terrain tile.
- minor code cleanup
> Bug fixing

- src/engine/tileManager.cxx
- src/engine/uiManager.cxx
Fix JSON errors when parsing files.
During refactoring, json parsing broke in a curious way. This only effected linux and windows debug build.
> Fix json errors

- src/engine/basics/camera.cxx
- src/engine/basics/isoMath.cxx
- src/engine/engine.cxx
- src/engine/engine.hxx
- src/engine/eventManager.cxx
- src/game.cxx
1. removed newGame call from Engine constructor.
2. added nullptr check for map, in engine instance.
3. added newGame callback function.
> #164 fix, Load Game starts a new game

- .gitignore
- CMakeLists.txt
- cmake/pmm.cmake
- conanfile.txt.in
> 🔧 Update to PMM 1.4.2 

- src/engine/Engine.hxx
- src/engine/GameObjects/MapNode.hxx
- src/engine/basics/Camera.hxx
- src/engine/basics/LOG.hxx
- src/engine/basics/Settings.hxx
- src/engine/basics/Timer.hxx
I've only done a little bit for these, but let me know if I need to reword things or if I need to change something.
> :pencil: New Doxygen Documentation

- src/Game.cxx
- src/Scripting/ScriptEngine.cxx
- src/engine/Engine.hxx
- src/engine/GameObjects/MapNode.hxx
- src/engine/Map.cxx
- src/engine/Sprite.cxx
- src/engine/UIManager.cxx
- src/engine/audio/SoundEffect.cxx
- src/engine/basics/Camera.hxx
- src/engine/basics/LOG.hxx
- src/engine/basics/Settings.hxx
- src/engine/basics/Timer.hxx
- src/engine/basics/signal.hxx
- src/engine/map/TerrainGenerator.cxx
- src/engine/ui/basics/ButtonGroup.cxx
I mostly just merged if statements and tried to do some simple fixes for some of the code smells in SonarCloud. Relevant to issue #232 
(My commits from PR #244 got in here too by mistake.)
> :rotating_light: Fix sonarcloud issues

- src/engine/EventManager.cxx
- src/engine/Map.cxx
- src/engine/UIManager.cxx
- src/engine/WindowManager.cxx
- src/engine/basics/Camera.cxx
- src/engine/ui/basics/Layout.hxx
- src/engine/ui/widgets/TextField.cxx
Fixed more SonarCloud issues. There are some others that seem to be easy fixes, but I wanted to make sure that they weren't left like that for a reason. 
#232
> More Sonarcloud fixes

- .gitignore
- src/engine/EventManager.cxx
- src/engine/ui/widgets/Slider.cxx
- src/engine/ui/widgets/Slider.hxx
In response to issue #76 
The slider works in two ways: if you click somewhere on the line, and if you click and drag the button.
(The formatting on `EventManager.cxx` looks weird in the compare, but looked fine in VS, so I'm not sure what's going on with that if it's just a me thing or not.)
> Slider UIElement

- data/languages/Cytopia.pot
- data/resources/data/TileData.json
I've added descriptions/titles to my buildings in TileData.json.  I also made a few small edits to other descriptions and fixed the misspelling of my username (From "KingTut 101", to "Kingtut 101").  I avoided editing some things, like the trees and the water towers, because those seemed like temporary things.
> Added descriptions/titles in TileData.json

- conanfile.txt.in
> 🔧 Use sdl2_mixer/2.0.4@bincrafters/stable

- appveyor.yml
> 🌐 Added translations to itch build

- .travis.yml
- appveyor.yml
- src/CMakeLists.txt
> Added copy_resources target to ALL

- cmake/pmm.cmake
See https://github.com/AnotherFoxGuy/pmm/releases/tag/1.7.0 for the changelog
> ⬆️ Upgrade PMM to 1.7.0

- data/resources/data/TileData.json
- tools/tile-tagger.py
The list of removed words can probably be better. I've written it based on the first 100 or so tiles, but it might be more practical to add words to it as the game is played and words pop up that shouldn't be there.
Should resolve #319 .
> Created the tile tagging script and updated TileData.json.

- CMakeLists.txt
- Doxyfile
- conanfile.txt.in
- src/CMakeLists.txt
I created this new branch (v0.3) for features that shouldn't affect v0.2
> Vulkan support

- appveyor.yml
Just checking to see if it builds without any conan pkg changes
> 👷 Build 32bit exe on appveyor

- conanfile.txt.in
- src/engine/GameObjects/MapNode.cxx
- src/engine/GameObjects/MapNode.hxx
- src/engine/Map.cxx
- src/engine/common/Constants.hxx
- src/engine/common/JsonSerialization.hxx
Fixes #313
Also, in DEBUG configuration, the savegame is now saved as uncompressed json for easier debugging.
> Fix savegames - mapNodes are now correctly serialized.

- README.md
- ReleaseNotes.txt
Updated two files with new, up-to-date information. ReleaseNotes should now have the latest revision of the v0.2 changelog, and README should have all of our social media accounts and an updated list of key/planned features.
> Updated README and ReleaseNotes

- src/Game.cxx
- src/engine/EventManager.cxx
- src/engine/basics/Settings.hxx
Implemented for #364 
This is only a temporary solution since the UI gets a total overhaul.
> Toggle UI with the 'h' button

- data/resources/data/TileData.json
- src/engine/Engine.hxx
- src/engine/EventManager.cxx
- src/engine/EventManager.hxx
- src/engine/GameObjects/MapNode.cxx
- src/engine/GameObjects/MapNode.hxx
- src/engine/Map.cxx
- src/engine/Map.hxx
- src/engine/TileManager.cxx
- src/engine/TileManager.hxx
- src/engine/basics/isoMath.cxx
- src/engine/basics/isoMath.hxx
- src/engine/basics/tileData.hxx
added highlighting for buildings bigger than 1x1, prevent placement over these kind of buildings.
Note: this PR does not support Bresenham Line selection mode for buildings bigger than 1x1.
> Placement improvements

- data/resources/data/TerrainGen.json
- data/resources/data/TileData.json
- src/engine/Map.cxx
- src/engine/basics/Camera.cxx
- src/engine/basics/isoMath.cxx
- src/engine/basics/isoMath.hxx
Fixes #374
During analysis, i found some code that needs refactoring.
> [WIP} Fix tile selection + refactoring

- data/resources/data/TerrainGen.json
- data/resources/settings.json
I updated the settings and terrain gen json files with my new biomes. I will be adding more of them in the future.
> New Biomes

- data/resources/data/TileData.json
- src/engine/EventManager.cxx
- src/engine/GameObjects/MapNode.cxx
- src/engine/GameObjects/MapNode.hxx
- src/engine/Map.cxx
- src/engine/Map.hxx
- src/engine/Sprite.cxx
- src/engine/Sprite.hxx
- src/engine/UIManager.cxx
- src/engine/common/JsonSerialization.hxx
- src/engine/common/enums.hxx
1. updated enum Layer.
2. removed demy_node from code + TileData.json.
3. added parameter shouldRender to NodeData that specify if current Tile should be set the Texture to (used in building bigger than 1x1).
4. fixed load/save game accordingly.
> Buildings bigger than 1x1 refactoring

- src/engine/EventManager.cxx
- src/engine/EventManager.hxx
- src/engine/Map.cxx
- src/engine/basics/isoMath.cxx
- src/engine/basics/isoMath.hxx
Refactoring
Fixes #403 
Also fixes a bug where sometimes only the first element of the line was placed instead of the whole line
> Refactor tile selection

- src/engine/GameObjects/MapNode.cxx
> Fix crash when elevating diagonal terrain

- CMakeLists.txt
- ReleaseNotes.txt
- data/resources/data/TileData.json
> v0.2.1 preparations

- src/engine/TileManager.cxx
- src/engine/basics/tileData.hxx
- Make ground decoration a string array
- Add happyness property
> Make ground decoration an array

- src/Game.cxx
- src/Game.hxx
- src/main.cxx
Speedup closing the game from the main menu
> Bugfix: issue#469: x button from main menu does not work

- src/engine/GameObjects/MapNode.cxx
- src/engine/Map.cxx
I have tested it, but not sure why this condition was here at the first place
> Bugfix: issue#477 Autotiling only for same Tile ID

- src/CMakeLists.txt
- src/view/iView.cxx
- src/view/iView.hxx
This is the interface that all Views must implement.
> Added iView interface

- .clang-format
- .travis.yml
- CMakeLists.txt
- appveyor.yml
- cmake/pmm.cmake
- src/engine/Map.cxx
- tools/format-json.js
Reverts CytopiaTeam/Cytopia#516
> Revert "Merge master into v0.3"

- src/engine/Map.cxx
- src/engine/Map.hxx
This improves a performace a bit.
> Replace visible nodes vector with array

- get_dependencies.sh
- src/util/Color.cxx
> fix dependencies #2

- src/engine/basics/Settings.cxx
Changes:
+ Settings json file is pretty-formatted when saved
> JSON Settings formatting

- .travis.yml
- cmake/pmm.cmake
- tools/CI/upload-CI-apk.sh
- tools/CI/upload-CI-build.sh
This will now automatically install the latest version of cmake, conan and sccache
> 🔧 Use AnotherFoxGuy/ci-scripts for installing devtools

- data/languages/Cytopia.pot
- tools/l10n/extract_from_json.js
Add the comment as a extracted-comment instead of a translator-comment
> 🐛 Fixed .pot comment extraction

- external/header_only/moFileReader.hpp
moFileReader Changelog:
🔧 Proper implementation of contexts strings. Now it uses a separate 2D map for storing strings with context
🐛 Fixed MagicNumber check not working on Linux
🎨 Removed duplicate code
🔧 Added option to disable convenience Class
> ⬆️ Update moFileReader to 1.2.0

- .gitmodules
Add back vcpkg submodule
set it to the lattest relase 2022.02.03
> Add back vcpkg submodule

- src/engine/GameObjects/MapNode.hxx
- src/engine/Map.hxx
- src/engine/UIManager.hxx
- src/engine/audio/Soundtrack.hxx
- src/engine/basics/Settings.hxx
- src/engine/basics/signal.hxx
- src/engine/ui/basics/ButtonGroup.hxx
- src/engine/ui/widgets/Text.hxx
- src/services/GameClock.hxx
- src/util/Exception.hxx
- src/util/filesystem.hxx
Minor changes to doxygen comment blocks, such as fixing commands to make sure the comments actually showed up in the documentation.
> Fixed doxygen syntax

- src/engine/EventManager.hxx
- src/engine/UIManager.hxx
- src/engine/WindowManager.hxx
- src/engine/basics/GameStates.hxx
- src/engine/basics/point.hxx
- src/engine/basics/signal.hxx
- src/engine/basics/tileData.hxx
- src/engine/ui/basics/Layout.hxx
- src/engine/ui/basics/UIElement.hxx
Tried to go through all of the files and make some fixes all at once, so this should hopefully be the last doxygen related PR for a while, at least in terms of syntactical changes.
> Mass doxy fixes

- src/engine/GameObjects/MapNode.cxx
- src/engine/Map.hxx
- src/game/GamePlay.hxx
- src/game/ZoneManager.cxx
- src/game/ZoneManager.hxx
Add Zonetiles when setting tileID instead of scanning all tiles every tick
> Zone improvements

- data/resources/settings.json
- src/Game.cxx
- src/engine/basics/Settings.hxx
- src/engine/common/JsonSerialization.hxx
- src/game/ZoneManager.cxx
- src/services/AudioMixer.cxx
- src/services/AudioMixer.hxx
Read volume settings for ALL volume from settings and apply it at game startup.
> Volume control

- src/engine/EventManager.cxx
- src/engine/Map.cxx
- src/engine/Map.hxx
- src/engine/basics/isoMath.cxx
- src/engine/basics/isoMath.hxx
- src/engine/basics/point.hxx
park my changes in a branch so I can continue working
> Refactor point

- src/engine/GameObjects/MapNode.cxx
- src/engine/Map.cxx
Allow overplacement only for buildings that have the isOverplacable flag set
> Fix overplacement issues

- data/resources/data/TileData.json
- src/engine/TileManager.cxx
- src/engine/basics/tileData.hxx
- src/game/ZoneManager.cxx
Add new tiletypes
rename zonetype and zonedensity
> Update tile types

- README.md
I like having a list of all dependencies in the readme to help me build a project rapidly.
> README.md: Adding all dependencies

- src/engine/Map.cxx
- src/engine/Map.hxx
- src/engine/basics/PointFunctions.cxx
- src/engine/basics/PointFunctions.hxx
- src/engine/basics/point.hxx
Refactoring of map class to take points as parameters and simplifying things.
Add toIndex() function to points
> Map refactoring

- src/engine/GameObjects/MapNode.cxx
- src/engine/GameObjects/MapNode.hxx
- src/engine/Map.cxx
- src/engine/Sprite.cxx
- src/engine/Sprite.hxx
- src/engine/TileManager.cxx
- src/engine/common/enums.hxx
- src/engine/map/MapLayers.cxx
> Add more Layers

- src/engine/ui/widgets/Combobox.cxx
- tests/CMakeLists.txt
- tests/ui/widgets/Button.cxx
- tests/ui/widgets/Checkbox.cxx
- tests/ui/widgets/Combobox.cxx
- tests/ui/widgets/Slider.cxx
- tests/ui/widgets/Text.cxx
- tests/ui/widgets/Tooltip.cxx
Addressing #350 
I created unit tests for the main UI widgets. Certainly not completely done, but I at least wanted to get the ball rolling. Note that one test will fail--I looked at it and the (I feel) the test is still correct, and that the code of the actual widget needs to be changed so it passes (which I can take care of.) I know that our sonar cloud integration doesn't work so unfortunately won't update the test coverage badge we have, but still improves our coverage.
> Created unit tests for UI widgets

- data/resources/settings.json
- src/engine/Engine.cxx
- src/engine/GameObjects/MapNode.hxx
- src/engine/common/JsonSerialization.hxx
Update map when creating a new game (while ingame) or loading a game. Previously the screen stayed blank, because the visible mapnodes were not updat4ed
> Fix new game and load game buttons

- data/resources/data/UILayout.json
- src/engine/UIManager.cxx
- src/engine/basics/Settings.cxx
- src/engine/common/Constants.hxx
- tests/CMakeLists.txt
- tests/engine/basics/Settings.cxx
Fix vsync button
fix reading settings from data dir
add unittest for settings
> Fix vsync button

- src/engine/UIManager.cxx
- src/engine/ui/basics/UIElement.cxx
- src/engine/ui/basics/UIElement.hxx
- src/engine/ui/widgets/Button.hxx
- src/engine/ui/widgets/Checkbox.cxx
- src/engine/ui/widgets/Checkbox.hxx
- src/engine/ui/widgets/Slider.cxx
- src/engine/ui/widgets/Slider.hxx
Namely the two big changes were to Slider and drawImageButtonFrame. I changed the name and functionality (slightly) of a confusing method in Slider, and I moved drawImageButtonFrame from being a method all UIElements had to just a method that Buttons have.
> More minor refactoring/changes for UI widgets

- src/engine/GameObjects/MapNode.cxx
- src/engine/GameObjects/MapNode.hxx
- src/game/PowerManager.cxx
- src/game/PowerManager.hxx
First part of my refactor. For the new recreate map -> update managers I will need to refactor a lot. this should be a separate PR though.
> Add a isConductive() check to mapNode and a functionality to recreate map

- .github/workflows/build-game.yml
- .github/workflows/sonarcloud.yml
- src/engine/WindowManager.cxx
- tests/CMakeLists.txt
This hopefully fixes the randomly failing tests on Linux once and for all
> :bug: Fixed test failing on Linux

- src/main.cxx
- src/util/Exception.cxx
- src/util/Exception.hxx
why: better user experience and bug fixing
> platform: crashhandler: show extended info about crash in log

- .github/workflows/sonarcloud.yml
- src/CMakeLists.txt
- src/engine/GameObjects/MapGrid.hxx
- src/engine/GameObjects/MapGrid.inl.hxx
- src/game/PowerGrid.cxx
- src/game/PowerGrid.hxx
- src/game/PowerManager.cxx
- src/game/ZoneArea.cxx
- src/game/ZoneArea.hxx
- src/game/ZoneManager.cxx
MapGrid.hxx and MapGrid.inl.hxx
PowerGrid and ZoneArea derived from MapGrid
Move same function in PowerGrid and ZoneArea to MapGrid
> MapGrid base class (#922)

- src/engine/GameObjects/MapNode.cxx
- src/engine/Map.cxx
- src/engine/UIManager.cxx
- src/engine/basics/PointFunctions.cxx
- src/game/ZoneManager.cxx
- src/util/desktop/Filesystem.cxx
There are some existed warnings when compiling Cytopia, It's not convenient for developers to find whether their'code has introduced compile warnings or not. So I modified some codes and avoid all compile warnings.
> chore: avoid compile warnings

- .github/workflows/build-game.yml
Make stage names more readable on phones
> Change names of pipelines in github actions

- data/resources/data/UILayout.json
- external/imgui/imgui.cpp
- external/imgui/imgui.h
- src/CMakeLists.txt
- src/Game.cxx
- src/Game.hxx
- src/engine/EventManager.cxx
- src/engine/EventManager.hxx
- src/engine/UIManager.cxx
- src/engine/UIManager.hxx
- src/game/ui/PauseMenu.cxx
- src/game/ui/PauseMenu.hxx
- src/game/ui/SettingsMenu.cxx
- src/game/ui/SettingsMenu.hxx
why:
pause menu was designed with native ui system, now
it can works via imgui. Also add openMenu/closeMenu
that management menu stacks with simple sequence of owners
> imgui: moved ingame pause menu to imgui logic

- data/resources/data/UILayout.json
- src/CMakeLists.txt
- src/MainMenu.cxx
- src/engine/UIManager.cxx
- src/game/ui/LoadMenu.cxx
- src/game/ui/LoadMenu.hxx
why: allow player to load city from dialog
https://github.com/CytopiaTeam/Cytopia/issues/78
> ui: mainmenu: add load dialog in mainmenu

- external/imgui/imgui_widgets.cpp
- src/CMakeLists.txt
- src/Game.cxx
- src/game/ui/GameTimeMenu.cxx
- src/game/ui/GameTimeMenu.hxx
- src/services/GameClock.cxx
- src/services/GameClock.hxx
task: https://github.com/CytopiaTeam/Cytopia/issues/843
> ui: add time controls area

- src/engine/UIManager.cxx
Minor edits to prefer const-default and more scope-local variables.
> uimanager: Prefer const and scope-local variables

- src/engine/map/MapFunctions.cxx
```
Build System:
- Compiler: `GCC 12.x`
```
* Currently code cannot compile.
* Replaced (miswritten?) datatype `Vector` with correct datatype `std::vector`.
> hotfix: Replace undefined datatype: `Vector`

- .github/workflows/build-game.yml
It is broken and I don't have a macOS device to test it with
> :construction_worker: Disable macos build for now
